<?php

function geraHTMLCaptiEdson(){

$myFile = "../base_scorm/m1/index.html";
$fh = fopen($myFile, 'w') or die("Não foi possível gerar o arquivo");

$linha1 =       "<!DOCTYPE html>\n";
$linha1b =       "<html lang='en'>\n";
$linha2 =        "<head> \n";
$linha3 =        "<meta charset='utf-8'>\n";
$linha4 =        "<meta http-equiv='X-UA-Compatible' content='IE=edge'>\n";
$linha5 =	     "<meta name='viewport' content='width=device-width, initial-scale=1'>\n";
$linha6 =        "<script src='../APIWrapper.min.js'></script>\n";
$linha7 =        "<script src='../SCOFunctions.min.js'></script>\n";
$linha8 =        "<link rel='stylesheet' href='../bootstrap/css/bootstrap.min.css' type='text/css' media='all' />\n";
$linha9 =        "<link rel='stylesheet' href='../estilos.min.css' type='text/css' media='all' />\n";
$linha10 =       "<link rel='stylesheet' href='../extras.min.css' type='text/css'>\n";
$linha11 =       "<link rel='stylesheet' href='../simulacao.min.css' type='text/css' media='all' />\n";
$linha12 =       "<link rel='stylesheet' href='../animacoes.min.css' type='text/css' media='all' />\n";
$linha13 =       "<link rel='stylesheet' href='../animacoes-evento.min.css' type='text/css' media='all' />\n";
$linha14 =       "<link rel='stylesheet' href='../player/mediaelementplayer.min.css' type='text/css' media='all' />\n";
$linha15 =       "<link rel='stylesheet' href='../plugins/plyr/plyr.css' type='text/css' media='all' />\n";
$linha16 =       "<link rel='stylesheet' href='../slick/slick.min.css' type='text/css'>\n";
$linha17 =       "<link rel='stylesheet' href='../slick/slick-theme.min.css' type='text/css'>\n";
$linha18 =       "<link rel='stylesheet' href='../plugins/timelinr/css/style.css' type='text/css' media='all'/>\n";
$linha19 =       "<link rel='stylesheet' href='../estilos-customizados.css' type='text/css' media='all' />\n";
$linha20 =  	 "<title>Formação de Facilitadores – Na Medida Planejamento Estratégico </title>\n";
$linha21 =    	 "</head>\n";
$linha22 =  	 "<body class='institucional' onLoad='SCORMFunctions.loadPage()' onunload='return SCORMFunctions.unloadPage()'> \n";
$linha23 = 	     "<div id='pagina'> \n";
$linha24 =  	 "<header> \n";
$linha25 = 		 "<div class='bloco-total topo'> \n";
$linha26 = 		 "<div class='bloco'> \n";
$linha27 = 		 "<div class='col_50 logo'> \n";
$linha28 = 		 "<a href='http://ead.sebraesp.com.br/' target='_blank'><img src='../img/logo-sebrae.png'></a> \n";
$linha29 = 		 "</div> \n";
$linha30 = 		 "<div class='col_50 aba'> \n";
$linha31 = 		 "<div class='aba-area-curso'>&nbsp;</div> \n";
$linha32 = 		 "</div>  \n";
$linha33 = 		 "</div> \n";
$linha34 = 		 "</div> \n";
$linha35 = 		 "<div class='bloco dados-curso'> \n";
$linha36 = 		 "<div class='col_50 curso'> \n";
$linha37 = 		 "<h4 class='texto-branco'>Formação de Facilitadores – Na Medida Planejamento Estratégico </h4> \n";
$linha38 = 		 "</div> \n";
$linha39 = 		 "<div class='col_50 modulo'> \n";
$linha40 = 		 "<h5>Olá, <span id='nome-aluno'>aluno</span></h5> \n";
$linha41 = 		 "<h4>Módulo 1 - Planejamento Estratégico – Encontros  1 e 2</h4> \n";
$linha42 = 		 "<h6><span id='porcentagem-modulo'></span>% concluído</h6> \n";
$linha43 = 		 "</div> \n";
$linha44 = 		 "</div> \n";
$linha45 = 		 "</header> \n";
$linha46 = 		 "<div class='bloco'> \n";
$linha47 = 		 "<div class='col_50 esquerda'></div> \n";
$linha48 = 		 "<div class='col_50 direita'></div> \n";
$linha49 = 		 "</div> \n";
$linha50 = "<div class='container-wrapper'> \n";
$linha51 = "<section id='telas' class='container principal' data-tela-anterior='0' data-tela-atual='0' data-possui-controles='1' data-codigo='c037pe_m'> \n";

// Montagem das telas
$linha52 = "<article class='tela escura' data-tempo-tela-mudo='1000' data-tempo-tela='15000'  \n";
$linha53 = "data-grupo='Módulo 1 - Planejamento Estratégico – Encontros  1 e 2'> <div class='fundo fundo-curso-037 box-imagem efeitos \n";     
$linha54 = "entrada-porcima-perspectiva saida-porbaixo-perspectiva entrada-duracao-500 saida-duracao-500saida-atraso-250'> \n"; 
$linha55 = "<img  class='ajusta-largura' src='imagens/037_4PE_M1_Tela1_548375419.jpg' style='opacity: 0.5;'/> \n"; 
$linha56 = "</div>\n"; 
$linha57 = "<div class='bloco-para-verticalizar'> \n"; 
$linha58 = "<div class='bloco-verticalizado texto-centralizado espaco-lateral'> \n"; 
$linha59 = "<h3 class='efeitos  \n"; 
$linha60 = "entrada-peladireita-elastico \n";  
$linha61 = "entrada-duracao-500 \n"; 
$linha62 = "saida-porcima-elastico  \n"; 
$linha63 = "saida-duracao-250  \n"; 
$linha64 = "saida-atraso-250 \n"; 
$linha65 = "sem-espacos-verticais'>Bem-vindo ao curso \n"; 					
$linha66 = "</h3> \n"; 
$linha67 = "<h3 class='texto-maior efeitos  \n"; 
$linha68 = "entrada-porcima-elastico  \n"; 
$linha69 = "entrada-duracao-500  \n"; 
$linha70 = "saida-porcima-elastico  \n"; 
$linha71 = "entrada-atraso-250 \n"; 
$linha72 = "saida-duracao-500  \n"; 
$linha73 = "saida-atraso-250 sem-espacos-verticais'>Formação de Facilitadores – Na Medida Planejamento Estratégico </h3> \n"; 
$linha74 = "<button class='bt-avancar bt-grande sombra centralizado texto-centralizado efeitos  \n"; 
$linha75 = "entrada-porbaixo-elastico \n";  
$linha76 = "entrada-atraso-750 \n"; 
$linha77 = "entrada-duracao-500 \n"; 
$linha78 = "saida-duracao-250  \n"; 
$linha79 = "saida-porbaixo-elastico  \n"; 
$linha80 = "espaco-acima'> \n"; 
$linha81 = "Iniciar curso \n"; 
$linha82 = "</button> \n"; 
$linha83 = "</div> \n"; 
$linha84 = "</div> \n"; 
$linha85 = "<!--<div class='audioEnunciado efeitos entrada-duracao-500 entrada-atraso-500 entrada-audio saida-imediata'> \n"; 
$linha86 = "<audio> \n"; 
$linha87 = "<source src='audios/.mp3' type='audio/mpeg'> \n"; 
$linha88 = "</audio> \n";    
$linha89 = "</div>--> \n"; 
$linha90 = "</article>\n"; 
// Fim das telas

$linha91 = "<div class='acessorios'> \n";
$linha92 = "<button id='bt-sumario' class='bt-sumario'>S</button> \n";
$linha93 = "<button id='bt-glossario' class='bt-glossario'>G</button> \n";
$linha94 = "<button id='bt-tutorial' class='bt-tutorial'>T</button> \n";
$linha95 = "<button id='bt-audio' class='bt-audio'>[</button> \n";
$linha96 = "</div> \n";
$linha97 = "<div class='controles'> \n";
$linha98 = "<span class='contador'></span> \n";
$linha99 = "<select id='comboTelas' class='combo-pular'></select> \n";
//$linha100 =	" \n";
$linha101 =	"<span id='totalDeTelas'></span> \n";
//$linha102 =	"</span> \n";
$linha103 =	"<button class='bt-recarregar'>&#47;&#92;</button> \n";
$linha104 =	"<button class='bt-retroceder'>&lt;</button> \n";
$linha105 =	"<button class='bt-tocarpausar'>&gt;||</button> \n";
$linha106 =	"<button class='bt-avancar'>&gt;</button> \n";
$linha107 =	"</div> \n";
$linha108 =	"<div class='barraProgresso'><span></span></div> \n";
$linha109 =	"</section> \n";
$linha110 =	"</div> \n";
$linha111 =	"<div class='links-wrapper'> \n";
$linha112 =	"<div class='bloco'> \n";
$linha113 =	"<div class='col_50'> \n";
$linha114 =	"<div class='bloco'> \n";
$linha115 =	"<div class='col_50 col_ebook'> \n";
$linha116 =	"<!-- <a href='../ebook/ebook.pdf' target='_blank'> --><img src='../img/ico-ebook.png'/><!--</a>--> \n";
$linha117 =	"<h5><em>E-book</em></h5> \n";
$linha118 =	"<p>Conteúdo do curso em formato de <em>E-book</em>.</p> \n";
$linha119 =	"</div> \n";
$linha120 =	"<div class='col_50 col_anexos'> \n";
$linha121 =	"<img src='../img/ico-anexos.png'/> \n";
$linha122 =	"<h5>Anexos</h5> \n";
$linha123 =	"<p>Complementos para aprofundar seus conhecimentos.</p> \n";
$linha124 =	"</div> \n";
$linha125 =	"</div> \n";
$linha126 =	"</div> \n";
$linha127 =	"</div> \n";
$linha128 =	"</div> \n";
$linha129 =	"</div> \n";
$linha130 =	"<audio id='audioblank' src='../blank.mp3' type='audio/mpeg'></audio> \n";
$linha131 =	"<footer> \n";
$linha132 =	"<span class='logo'> \n";
$linha133 =	"<a href='#'><img src='../img/logo-rodape.png'/></a> \n";
$linha134 =	"</span> \n";
$linha135 =	"<span class='social'> \n";
$linha136 =	"<a href='https://pt-br.facebook.com/sebraesp' target='_blank'><img src='../img/ico-fb.png'/></a> \n";
$linha137 =	"<a href='https://twitter.com/sebraesp' target='_blank'><img src='../img/ico-tw.png'/></a> \n";
$linha138 =	"<a href='https://www.linkedin.com/in/sebraesp' target='_blank'><img src='../img/ico-in.png'/></a> \n";
$linha139 =	"</span> \n";
$linha140 =	"</footer> \n";
$linha141 =	"<div id='mascara-iniciar'><span></span><button class='bt-grande'>Iniciar</button></div> \n";
$linha142 = "<script src='https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js'></script> \n";
$linha143 = "<script src='../bootstrap/js/bootstrap.min.js'></script> \n";
$linha144 = "<script src='../player/mediaelement-and-player.min.js'></script> \n";
$linha145 = "<script src='../plugins/timelinr/js/jquery.timelinr-0.9.6.js'></script> \n";
$linha146 = "<script src='../plugins/plyr/plyr.min.js'></script> \n";
$linha147 = "<script src='https://cdn.rangetouch.com/0.0.9/rangetouch.js' async></script> \n";
$linha148 = "<script src='../slick/slick.min.js' type='text/javascript' charset='utf-8'></script> \n";
$linha149 = "<script src='../zoom/jquery.zoom.min.js' type='text/javascript' charset='utf-8'></script> \n";
$linha150 = "<script src='../imagemap/jquery.rwdImageMaps.min.js'></script> \n";
$linha151 = "<script src='../script.min.js'></script> \n";
$linha152 = "<script src='../extras.min.js'></script> \n";
$linha153 = "<script src='../configuracoes.js'></script> \n";
$linha154 = "<script src='../carregar.js'></script> \n";
$linha155 = "</body> \n";
$linha156 = "</html> \n";




fwrite($fh, $linha1);
fwrite($fh, $linha1b);
fwrite($fh, $linha2);
fwrite($fh, $linha3);
fwrite($fh, $linha4);
fwrite($fh, $linha5);
fwrite($fh, $linha6);
fwrite($fh, $linha7);
fwrite($fh, $linha8);
fwrite($fh, $linha9);
fwrite($fh, $linha10);
fwrite($fh, $linha11);
fwrite($fh, $linha12);
fwrite($fh, $linha13);
fwrite($fh, $linha14);
fwrite($fh, $linha15);
fwrite($fh, $linha16);
fwrite($fh, $linha17);
fwrite($fh, $linha18);
fwrite($fh, $linha19);
fwrite($fh, $linha20);
fwrite($fh, $linha21);
fwrite($fh, $linha22);
fwrite($fh, $linha23);
fwrite($fh, $linha24);
fwrite($fh, $linha25);
fwrite($fh, $linha26);
fwrite($fh, $linha27);
fwrite($fh, $linha28);
fwrite($fh, $linha29);
fwrite($fh, $linha30);
fwrite($fh, $linha31);
fwrite($fh, $linha32);
fwrite($fh, $linha33);
fwrite($fh, $linha34);
fwrite($fh, $linha35);
fwrite($fh, $linha36);
fwrite($fh, $linha37);
fwrite($fh, $linha38);
fwrite($fh, $linha39);
fwrite($fh, $linha40);
fwrite($fh, $linha41);
fwrite($fh, $linha42);
fwrite($fh, $linha43);
fwrite($fh, $linha44);
fwrite($fh, $linha45);
fwrite($fh, $linha46);
fwrite($fh, $linha47);
fwrite($fh, $linha48);
fwrite($fh, $linha49);
fwrite($fh, $linha50);
fwrite($fh, $linha51);
fwrite($fh, $linha52);
fwrite($fh, $linha53);
fwrite($fh, $linha54);
fwrite($fh, $linha55);
fwrite($fh, $linha56);
fwrite($fh, $linha57);
fwrite($fh, $linha58);
fwrite($fh, $linha59);
fwrite($fh, $linha60);
fwrite($fh, $linha61);
fwrite($fh, $linha62);
fwrite($fh, $linha63);
fwrite($fh, $linha64);
fwrite($fh, $linha65);
fwrite($fh, $linha66);
fwrite($fh, $linha67);
fwrite($fh, $linha68);
fwrite($fh, $linha69);
fwrite($fh, $linha70);
fwrite($fh, $linha71);
fwrite($fh, $linha72);
fwrite($fh, $linha73);
fwrite($fh, $linha74);
fwrite($fh, $linha75);
fwrite($fh, $linha76);
fwrite($fh, $linha77);
fwrite($fh, $linha78);
fwrite($fh, $linha79);
fwrite($fh, $linha80);
fwrite($fh, $linha81);
fwrite($fh, $linha82);
fwrite($fh, $linha83);
fwrite($fh, $linha84);
fwrite($fh, $linha85);
fwrite($fh, $linha86);
fwrite($fh, $linha87);
fwrite($fh, $linha88);
fwrite($fh, $linha89);
fwrite($fh, $linha90);
fwrite($fh, $linha91);
fwrite($fh, $linha92);
fwrite($fh, $linha93);
fwrite($fh, $linha94);
fwrite($fh, $linha95);
fwrite($fh, $linha96);
fwrite($fh, $linha97);
fwrite($fh, $linha98);
fwrite($fh, $linha99);
//fwrite($fh, $linha100);
fwrite($fh, $linha101);
//fwrite($fh, $linha102);
fwrite($fh, $linha103);
fwrite($fh, $linha104);
fwrite($fh, $linha105);
fwrite($fh, $linha106);
fwrite($fh, $linha107);
fwrite($fh, $linha108);
fwrite($fh, $linha109);
fwrite($fh, $linha110);
fwrite($fh, $linha111);
fwrite($fh, $linha112);
fwrite($fh, $linha113);
fwrite($fh, $linha114);
fwrite($fh, $linha115);
fwrite($fh, $linha116);
fwrite($fh, $linha117);
fwrite($fh, $linha118);
fwrite($fh, $linha119);
fwrite($fh, $linha120);
fwrite($fh, $linha121);
fwrite($fh, $linha122);
fwrite($fh, $linha123);
fwrite($fh, $linha124);
fwrite($fh, $linha125);
fwrite($fh, $linha126);
fwrite($fh, $linha127);
fwrite($fh, $linha128);
fwrite($fh, $linha129);
fwrite($fh, $linha130);
fwrite($fh, $linha131);
fwrite($fh, $linha132);
fwrite($fh, $linha133);
fwrite($fh, $linha134);
fwrite($fh, $linha135);
fwrite($fh, $linha136);
fwrite($fh, $linha137);
fwrite($fh, $linha138);
fwrite($fh, $linha139);
fwrite($fh, $linha140);
fwrite($fh, $linha141);
fwrite($fh, $linha142);
fwrite($fh, $linha143);
fwrite($fh, $linha144);
fwrite($fh, $linha145);
fwrite($fh, $linha146);
fwrite($fh, $linha147);
fwrite($fh, $linha148);
fwrite($fh, $linha149);
fwrite($fh, $linha150);
fwrite($fh, $linha151);
fwrite($fh, $linha152);
fwrite($fh, $linha153);
fwrite($fh, $linha154);
fwrite($fh, $linha155);
fwrite($fh, $linha156);



fclose($fh);
}

geraHTMLCaptiEdson();


?>